name: test

on:
  push:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
        - name: test
          run: |
            echo ${{ github.run.id }}
            echo ${{ github.repository }}
            echo ${{ github.workflow }}
