name: test

on:
  push:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
        - name: test
          run: |
            echo ${{ env.GITHUB_WORKFLOW }}
            echo ${{ env.GITHUB_REPOSITORY }}
            echo ${{ env.GITHUB_RUN_ID }}
